apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-go
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: hello-go
  newName: quay.io/jkeam/hello-go
  newTag: latest
